spec:
  template:
    spec:
      containers:
        - name: central
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/cloud/service_account.json
          volumeMounts:
            - name: bound-sa-token
              readOnly: true
              mountPath: /var/run/secrets/openshift/serviceaccount
            - name: cloud-credentials
              readOnly: true
              mountPath: /var/run/secrets/cloud
      volumes:
        - name: bound-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: openshift
                  expirationSeconds: 3600
                  path: token
            defaultMode: 420
        - name: cloud-credentials
          secret:
            secretName: gcp-cloud-credentials
            defaultMode: 420
